version: '3.3'

services:
  solace:
    image: solace-openflowj:latest
    build:
      context: ./solace-openflowj
    ports:
      - "6633:6633"
    networks:
      - solace-net
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - redis
      - telegraf

  redis:
    image: redis:latest
    networks:
      - solace-net

  influxdb:
    image: influxdb:latest
    env_file:
      - 'influxdb/env.influxdb'
    networks:
      - solace-net
    volumes:
      - ./influxdb/data:/var/lib/influxdb

  telegraf:
    image: telegraf:latest
    networks:
      - solace-net
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    env_file:
      - 'grafana/env.grafana'
    networks:
      - solace-net
    volumes:
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - influxdb
      - telegraf

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - solace-net

networks:
  solace-net:
